#!/bin/bash

# The value of the returned slot attribute is a JSON list. As there
# will only ever be one directory specified, this script uses grep
# and cut to strip out the service name from the list:
#
# [ "$SNAP_DATA/edgex-application-service" ]
#
SLOT_ATTR=$(snapctl get --slot :edgex-secretstore-token source.write)
SERVICE_NAME=$(echo $SLOT_ATTR | grep -o "/[^\"]*" | cut -d'/' -f2)

APP_SVC_TOKEN="/tmp/$SERVICE_NAME-secrets-token.json"
TARGET_PATH="$SNAP_DATA/secrets/$SERVICE_NAME/secrets-token.json"

# This connection can happen before or after security-secretstore-setup
# (a oneshot service that configures Vault) has already run. The first
# case happens when the content interface is auto-connected and the
# external app or device service snap is installed before the edgexfoundry
# snap.
#
# The latter happens when the order is swapped *and* the connection
# is manually connected. In this case since security-secretstore-setup
# (which runs file-token-provider) has already run, the token for
# external snap will have already been generated, and thus will be
# hidden when the content interface directory from the external snap
# is bind mounted on top of the existing /secrets directory.
#
# The corresponding prepare hook (which runs before the bind mount) for
# this content interface is used to copy the token to /tmp.
#
# This script checks for the token in /tmp, and if found, moves it to
# the new bind mounted directory.
#
# NOTE - one final comment, app-service-configurable is included in the
# edgexfoundry snap to provide for Kuiper integration. It's disabled by
# default, and is hard-code to use the 'rules-engine' profile. Due to
# the way vault tokens work, both the internal app-service-configurable
# instance, and the instance in the app-service-configurable snap are
# able to share the same token.
if [ -f "$APP_SVC_TOKEN" ]; then
    logger "edgex-secretstore-token: $APP_SVC_TOKEN copied to $TARGET_PATH"
    mv "$APP_SVC_TOKEN" "$TARGET_PATH"
fi
