#!/bin/bash

APP_SVC_TOKEN="$SNAP_DATA/secrets/edgex-application-service/secrets-token.json"

# Since this connection may happen *after* security-secretstore-setup
# (and hence file-token-provider) has run, the token for app-service-cfg
# probably has already been generated, meaning it won't appear in the
# bind-mounted directory in app-service-cfg's slot directory.
#
# So, this script is a big hammer which deletes the token and then
# restarts security-secretstore-setup to regenerate all the tokens,
# which results in the token being accessible from the asc snap.
logger "edgex-secretstore-token: $APP_SVC_TOKEN"
rm -f "$APP_SVC_TOKEN"

# Check for success of the rm operation as none of the standard
# test options (-f, -e, -r, -w) seem to work properly to test
# for existence of this file. This is probably due to permissions
# of the parent directory, but should be first validated before
# this comment is removed.
#
# Note - also tried was using 'rm <token>' and then checking the
# status. This also fails because only 'rm -f' seems to work to
# delete the file, and the status of the command is always 0,
# even if the file doesn't exist!
snapctl restart "$SNAP_NAME.security-secretstore-setup"

