#!/bin/bash

# The value of the returned slot attribute is a JSON list. As there
# will only ever be one directory specified, this script uses grep
# and cut to strip out the service name from the list:
#
# [ "$SNAP_DATA/edgex-device-camera" ]
#
SLOT_ATTR=$(snapctl get --slot :edgex-secretstore-token source.write)
SERVICE_NAME=$(echo $SLOT_ATTR | grep -o "/[^\"]*" | cut -d'/' -f2)
logger "prepare-plug-edgex-secretstore-token: SERVICE_NAME=$SERVICE_NAME"

APP_SVC_TOKEN="$SNAP_DATA/secrets/$SERVICE_NAME/secrets-token.json"
TARGET_PATH="/tmp/$SERVICE_NAME-secrets-token.json"

# This connection can happen before or after security-secretstore-setup
# (a oneshot service that configures Vault) has already run. The first
# case happens when the content interface is auto-connected and the
# external application or device service snap is installed before the
# edgexfoundry snap. In this case there's no action required as
# security-secretstore-setup will write it's token to the source dir
# which has been bind mounted over the dir of the same name in this snap.
#
# The latter happens when the order is swapped *and* the connection
# is manually connected. In this case since security-secretstore-setup
# (which runs file-token-provider) has already run, the token for the
# external snap will have already been generated, and thus be hidden
# when the content interface directory from the external snap is bind
# mounted on top of the existing /secrets directory.
#
# Since this hook is called before the bind mount has happened, it checks
# to see if the file exists, and if so, copies it to  /tmp.
#
# NOTE - one final comment, app-service-configurable is included in the
# edgexfoundry snap to provide for Kuiper integration. It's disabled by
# default, and is hard-coded to use the 'rules-engine' profile. Due to
# the way vault tokens work, both the internal app-service-configurable
# instance, and the instance in the app-service-configurable snap are
# able to share the same token.
if [ -f "$APP_SVC_TOKEN" ]; then
    logger "edgex-secretstore-token: token found in $APP_SVC_TOKEN; moving to $TARGET_PATH"
    mv "$APP_SVC_TOKEN" "$TARGET_PATH"
fi
