#!/bin/bash

# This connection can happen before or after security-secretstore-setup
# (a oneshot service that configures Vault) has already run. The first
# case happens when the content interface is auto-connected and the
# edgex-app-service-configurable snap is installed before the edgexfoundry
# snap. In this case there's no action required as security-secretstore-
# -setup will write it's token to the source dir which has been bind
# mounted over the dir of the same name in this snap.
#
# The latter happens when the order is swapped *and* the connection
# is manually connected. In this case since security-secretstore-setup
# (which runs file-token-provider) has already run, the token for
# app-service-cfg will have already been generated, and thus be hidden
# when the content interface directory from the app-service-configurable
# snap is bind mounted on top of the existing /secrets directory.
#
# Since this hook is called before the bind mount has happened, it checks
# to see if the file exists, and if so, copies it to  /tmp.
#
# NOTE - one final comment, app-service-configurable is included in the
# edgexfoundry snap to provide for Kuiper integration. It's disabled by
# default, and is hard-coded to use the 'rules-engine' profile. Due to
# the way vault tokens work, both the internal app-service-configurable
# instance, and the instance in the app-service-configurable snap are
# able to share the same token.

SLOTDIRS=$(snapctl get :edgex-secretstore-token --slot source.write)
logger "prepare: SLOT_DIRS=$SLOTDIRS"
DIRS=$(cat "$SLOTDIRS" | jq -r '.[]')

logger "PREPARE: $DIRS"

for filename in app-http-export app-mqtt-export;
do
    APP_SVC_TOKEN="$SNAP_DATA/secrets/${filename}/secrets-token.json"
    TARGET_PATH="/tmp/${filename}-secrets-token.json"
    if [ -f "$APP_SVC_TOKEN" ]; then
        logger "edgex-secretstore-token: token found in $APP_SVC_TOKEN; moving to $TARGET_PATH"
        mv "$APP_SVC_TOKEN" "$TARGET_PATH"
    fi

done



